### ISSUE TITLE
MooTools in compatibility mode conflicts with React.js

### ISSUE THREAD

**Issue by dmitrizzle** [mootools/mootools-core#2773] opened 2016-09-30 01:46 UTC
Tested with MooTools 1.5.2 and 1.6.0 in compat mode. Both times I get error (see screenshot) which caused click events coded in React to seise firing after the first time.

However, when I use MT without the compat mode the issue disappears.
Also note that using MT without the compat mode with Angular produces another fatal error in browser console `$clear is not defined`.

<img width="671" alt="screen shot 2016-09-29 at 7 34 59 pm" src="https://cloud.githubusercontent.com/assets/8587882/18978049/b128073a-86e9-11e6-966d-3499ddcd59b6.png">
##

**Comment by dizel3d** [comment] 2017-07-27 11:59
Seems, the reason is that in compatibility mode MooTools replaces `Function.prototype.bind` (that used by React) with non-standard implementation. #2511
I guess it won't be fixed.

**Comment by timwienk** [comment] 2017-07-27 12:10
Indeed. Many problems like these are caused by using MooTools Core with compatibility additions while it is not necessary. You have to choose between compatibility with old MooTools or compliance with newer standards.

Since this issue is rather old, I assume it has been solved by now, but just to be clear:

Do **not** use MooTools libraries in compatibility mode when you do not need compatibility with old MooTools versions. Doing so is basically depriving yourself of newer JavaScript features.

**Closed by timwienk** 2017-07-27 12:10 UTC

**Comment by whizsid** [comment] 2019-01-03 04:33
I have fixed this issue by deleting the line
`delete Function.prototype.bind;`

**Comment by RaymondBenc** [comment] 2019-08-24 19:37
@whizsid you're my hero. Thank you!
