### ISSUE TITLE
Core with compatibility conflicts with google maps

### ISSUE THREAD

**Issue by Addviso** [mootools/mootools-core#2661] opened 2014-10-21 20:49 UTC
If you load a google map, ie, using a mootools class with many fonctionalities for this map, an error appears while loading the map (something like "e is not a function ..") . This occurs only when the compatibility mode is used in the core.

**Comment by ibolmo** [comment] 2015-01-14 21:33
We're also having issues reproducing this. IF you could provide the file(s) via Dropbox, etc. It'll help. Closing for now, since it seem worksforme.

**Closed by ibolmo** 2015-01-14 21:33 UTC
Labels: incomplete, invalid

**Comment by paulschwarz** [comment] 2015-11-25 10:56
I'm not sure if this is the same issue, but I've finally managed to squash an old sporadic bug by understanding that google maps checks if a .bind method has been implemented. See here https://code.google.com/p/gmaps-api-issues/issues/detail?id=7203#c9
I fixed my issue by making sure that Mootools was loaded before the Google Maps library. 
When using jsFiddle this would naturally be the case which might be the reason why you aren't able to reproduce the bug there.

**Comment by dhirendradaffodil** [comment] 2018-01-19 05:01
I am getting  Joomla Mootools not working with Google street view please check below link

Demo: http://jsbin.com/jukoqosuwi/edit?html,output

**Comment by abraraamer** [comment] 2021-01-19 10:39
> I am getting Joomla Mootools not working with Google street view please check below link
> 
> Demo: http://jsbin.com/jukoqosuwi/edit?html,output
Use the latest mootools core, v 1.6.
In some system plugin of yours, in onBeforeRender function, add the following code. have the latest mootools downloaded somewhere and entered in the path below. 
By the way, I am sure it's not only Joomla but anywhere older mootools and maps is being is used, has problems.

public function onBeforeRender() {
    $document = JFactory::getDocument();
    $headData = $document->getHeadData();
    $scripts = $headData['scripts'];
    
    $key = '/media/system/js/mootools-core.js';
    $attr = $scripts[$key];
    unset($scripts[$key]);
    unset($scripts['/media/system/js/mootools-more.js']);
    
    //download and load latest mootools
    $newscripts['/plugins/system/overrides/mootools-core-1.6.js'] = $attr;
    $newscripts = array_merge($newscripts, $scripts);
    
    
    $headData['scripts'] = $newscripts;
    $document->setHeadData($headData);
}
