### ISSUE TITLE
how can i make onchange select event firing?

### ISSUE THREAD

**Issue by newbie78** [mootools/mootools-core#2754] opened 2015-11-20 08:12 UTC
see this fiddle plz
http://jsfiddle.net/96s4kq8m/1/

is that firing really plssible? and if no then why?
thanks very mutch

**Comment by swhiteman** [comment] 2015-11-20 08:27
$('test').fireEvent('change');

This isn't a GitHub issue, so pls remove it. It should be on the mailing list mootools-users@googlegroups.com

**Comment by timwienk** [comment] 2015-11-20 08:35
In your JSFiddle you the following error is thrown: `TypeError: $(...).fireEvents is not a function`.

The problem is indeed what Sandy just mentioned, you should use `fireEvent`, not "fireEvent***s***".

I will close this issue. If you need any other support, please ask on the mailing list:
https://groups.google.com/forum/#!forum/mootools-users

**Closed by timwienk** 2015-11-20 08:35 UTC

**Comment by newbie78** [comment] 2015-11-20 08:45
yes. this is my mistake.
okay - thats work.

but why firing not work in this fiddle?
http://jsfiddle.net/96s4kq8m/2/

thanks again

**Comment by newbie78** [comment] 2015-11-20 08:47
yes. this is my mistake.
okay - thats work.

but why firing not work in this fiddle?
http://jsfiddle.net/96s4kq8m/4/

thanks again

**Comment by newbie78** [comment] 2015-11-20 10:14
please answ my q. in google mailing list forum no one answ me.

**Comment by DimitarChristoff** [comment] 2015-11-20 11:19
so i answered this like 5 yrs ago. http://stackoverflow.com/questions/2689010/mootools-programmatically-fired-events-not-working-with-event-delegation - looks like mootools does not normalise and bubble native change events just yet.

**Comment by newbie78** [comment] 2015-11-20 14:40
Dimitar, thanks for answer

http://jsfiddle.net/96s4kq8m/5/
How could i get the changed 'field' (see fiddle) by means of usual addEvent('change') ?

**Comment by newbie78** [comment] 2015-11-20 14:44
maybe will we need to reopen the issues?

**Comment by newbie78** [comment] 2015-11-20 15:35
http://jsfiddle.net/96s4kq8m/6/
fireEvent worked but undefined. why?
